package rabisco

var seeds = [...]string{
	"Afogar o ganso",
	"Água na boca",
	"Barco pirata",
	"Brigadeiro",
	"Burro quando foge",
	"Cabelereiro",
	"Cachoeira",
	"Cachorro sem dono",
	"Cada macaco no seu galho",
	"Carne de pescoço",
	"CD prensadão sem graveto",
	"Compasso composto",
	"Duas raquetes",
	"Esqueceram de mim",
	"Internauta",
	"Mamão com açucar",
	"Melzinho na chupeta",
	"Molhar o biscoito",
	"Piratas da internet",
	"Segunda-feira",
	"Sobrancelhas",
	"Surdez temporária",
	"Tempestade no copo d'água",
	"Última bolacha do pacote",
	"Um lugar do caralho",
	"Vira folha",
}
